### ISSUE TITLE
Language Constraints (node.js) ? 

### ISSUE THREAD

**Issue by shriram2301** [SVCE-ACM/A-December-of-Algorithms-2020#14]
Are there any language constraints? I plan on using node.js. I noticed that the .gitignore file doesn't have the configuration for node modules was not there? If so can I raise a PR to add node modules and package-lock.json to .gitignore file?

**Comment by bearlike** [comment]
Hello @shriram2301, 
You can use any Programming Language to solve our Daily Challenge. You can also raise Issues and send PRs, if you feel anything has to be changed. Our Coding Ninjas will review and merge them if required. Cheers!

**Comment by bearlike** [comment]
Issue Resolved.
