### ISSUE TITLE
Error on Output explanation of fourth problem

### ISSUE THREAD

**Issue by suren003** [SVCE-ACM/A-December-of-Algorithms-2020#19]
In output explanation of fourth problem you added 20 days to 20/12/2019 and made it to 10/01/2020 but logically december has 31 days. So 09/01/2020 would be the correct date of expiry. Change this as soon as possible.

**Comment by rohithmsr** [comment]
It is given in the problem statement that to assume each month has only 30 days.

> In output explanation of fourth problem you added 20 days to 20/12/2019 and made it to 10/01/2020 but logically december has 31 days. So 09/01/2020 would be the correct date of expiry. Change this as soon as possible.

**Comment by suren003** [comment]
Thank you for your clarification.

**Comment by bearlike** [comment]
**@suren003 Thank you for clarifying queries. Your support is greatly appreciated 💯**

**Comment by suren003** [comment]
You updated problems for december 6 to december 9 but that doesn't show in
my forked repo. How should i update that in my repo?

**Comment by suren003** [comment]
I found the way and forked the changes into my repository. Thanks.
