### ISSUE TITLE
Fix branch name in FAQ

### ISSUE THREAD

**Issue by kana800** [SVCE-ACM/A-December-of-Algorithms-2020#21]
correct me if i am wrong 😄 

```
git remote add upstream https://github.com/SVCE-ACM/A-December-of-Algorithms-2020.git
git fetch upstream
git merge upstream/master
```
But shouldn't it be `git merge upstream/main` 

if we use the following command `git merge upstream/master` , the following output will be given
```terminal
merge: upstream/master - not something we can merge
```

**Comment by bearlike** [comment]
@kana800 You're absolutely right, GitHub has changed their Default Base branch name from `master` to `main`. We'll definitely fix them with #18
