### ISSUE TITLE
Correction of Day_6 Sample I/O 1

### ISSUE THREAD

**Issue by rohithmsr** [SVCE-ACM/A-December-of-Algorithms-2020#23]
In the input, only 'B', 'C', 'D' vertices are present but in the graph we also have vertex 'A',
so,
should I add 'A' to the input 
or 
should assume there is vertex 'A' since 'B' is the least vertex in the input??

**Comment by Ganesh-Kumar6** [comment]
Hi @rohithmsr

Here is the given input
[ ['B','C'], [], ['D']

As mentioned in the question each index represents a vertex.

Index 0 is A and A is pointing to vertex B and C.
Index 1 is B and B is not pointing to any vertex so empty array.
Index 2 is C and C is pointing to vertex D.

This is how the input is given.

**Comment by rohithmsr** [comment]
Got it @Ganesh-Kumar6 .Could you give another sample input in the same format and its output?

**Comment by Ganesh-Kumar6** [comment]
Sure

Here is another input with its output

```
[["B","D"], ["C"], ["E"], [], []]
```

The possible solutions for this input are

A D B C E
A B D C E
A B C D E
A B C E D

**Comment by rohithmsr** [comment]
Thank you so much @Ganesh-Kumar6 .

**Comment by rohithmsr** [comment]
Isn't the sample input 1 is
```
[['B','C'], [], ['D'], []]
```
??? Since D isn't pointing to any vertex.

Thanks in advance. Sorry for reopening this issue again

**Comment by Ganesh-Kumar6** [comment]
Sorry it was a typo.

**Comment by Ganesh-Kumar6** [comment]
@bearlike the input for question 6 should be fixed to 
```
[ ['B','C'], [], ['D'], [] ]
```

**Comment by bearlike** [comment]
### Closing issue since resolved
