### ISSUE TITLE
Error in Testcase - Day 21 - Test Of Accuracy

### ISSUE THREAD

**Issue by rohithmsr** [SVCE-ACM/A-December-of-Algorithms-2020#64]
In the testcase, the first point given as 
```
30 40 10
```
but in the diagram, line is plotted for 
```
30 10 10
```
So if the first point is 30 40 10 , then 4 targets can be hit.
3 targets can be the maximum, only if the first point is 30 10 10

**Comment by Sandyy22** [comment]
There is an error in the Sample Input provided in the question. 
The first point should be 30 10 10 only.
It will be rectified at the earliest.

**Comment by dhirajv2000** [comment]
Thank you for spotting the error.
